name: TrackFlow Check

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Vérification simple
        run: echo "TrackFlow fonctionne parfaitement"